### ISSUE TITLE
States timeline returning Total

### ISSUE THREAD

**Issue by eventamplify** [digiphilo/covid#3]
Hello, it looks like the states timeline endpoint is now returning just the total for the state:

https://covapi.herokuapp.com/api/timeline/states/colorado

Returns: 

{"Colorado":{"cases":"2061","deaths":"44"}}

**Comment by b-rms** [comment]
Apologies, will get this fixed right away

**Comment by digiphilo** [comment]
Fixed, will add some unit and integration tests tonight and refrain from pushing changes until I'm more sure there aren't any regressions.
